language: python

matrix:
    include:
        - python: 3.5
          env: TOX_ENV=docs
        - python: 3.4
          env: TOX_ENV=py34
        - python: 3.5
          env: TOX_ENV=py35
        - python: 3.6
          env: TOX_ENV=py36
        - python: 3.5
          env: TOX_ENV=lint
    allow_failures:
        - python: 3.4
          env: TOX_ENV=py34

install:
    - pip install codecov nose tox
    - python setup.py install

script:
    - tox -e $TOX_ENV
after_success:
    - if [[ "$TOX_ENV" == "py35" ]]; then nosetests ./tests -v --with-coverage --cover-xml --cover-package=iqrf; fi
    - if [[ "$TOX_ENV" == "py35" ]]; then codecov; fi
